server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: BookQueryService
          uri: lb://BookQueryService
          predicates:
            - Path=/books/**
            - Method=GET
        - id: BookCommandService
          uri: lb://BookCommandService
          predicates:
            - Path=/books/**
            - Method=POST,PUT,DELETE,PATCH
        - id: ReviewService
          uri: lb://ReviewService
          predicates:
            - Path=/reviews/**
        - id: CustomerService
          uri: lb://CustomerService
          predicates:
            - Path=/customers/**
        - id: BorrowService
          uri: lb://BorrowService
          predicates:
            - Path=/borrows/**
  sleuth:
    sampler:
      probability: 1.0

